<?php
/**
 * This file is part of reliadmin project.
 * @author Stanislav Opletal <info@relisoft.cz>
 */

namespace App\Presenters;


use App\Core\Component\Profile\ProfileComponent;
use App\Core\Model\User\User;

class UserPresenter extends BasePresenter
{
    /** @var ProfileComponent @inject */
    public $profileComponent;

    /**
     * @param int $id
     * @throws \Nette\Application\AbortException
     */
    public function actionProfile(int $id): void{
        $model = new User();
        $this->loader->loadById($model,$id);
        if($model->getId()){
            $this->template->usr = $model;
        }else{
            $this->flashMessage($this->tr->trans('front.no_profile'),'error');
            $this->redirect('Homepage:default');
        }
    }

    public function beforeRender(): void
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
        if(!$this->getUser()->isLoggedIn()){
            //Cannot enter this presenter if user is not logged in
            $this->flashMessage($this->tr->trans('front.profile.must_login'),'error');
            $this->redirect('Homepage:default');
        }
    }

    protected function createComponentProfile(): ProfileComponent {
        return $this->profileComponent;
    }
}